image: node:alpine
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  - cp public/index.html
  artifacts:
    paths:
    - public
  only:
  - master 
  variables:
    PUBLIC_URL: "/personal-website"